### ISSUE TITLE
Gridsome ^0.4.1 no longer recognizing static properties in JS Classes

### ISSUE THREAD

**Issue by courcelan** [gridsome/gridsome#112]
## Description

When using Gridsome@0.4.0, JavaScript class declarations correctly use `static` property values. Om upgrading to 0.4.1/0.4.2, I receive a parse/compilation error. I'm using a `.babelrc` file and use `webpack-chain` in `gridsome.config.js` to tap into the `babel-loader` options to inform the loader to use a `babelrc` file.

This worked correctly in v0.3.6 and v0.4.0. Is Gridsome no longer accepting `.babelrc` imports? What may have changed between 0.4.0 and 0.4.1?

### Steps to reproduce

I have the following in a `.babelrc` file:
```
{
    "plugins": [
        ["@babel/plugin-proposal-class-properties"],
    ],
}
```

In my `gridsome.config.js`, in `chainWebpack`, I have:
```
config.module
            .rule("js")
            .use("babel-loader")
            .loader("babel-loader")
            .tap(
                options => {
                    options.babelrc = true
                    return options
                }
            )
```

My offending code:

```
import { Model } from '@vuex-orm/core'

export default class Form extends Model {
    // @desc    object name within Vuex
    static entity = "forms"

    // @desc    localized primary key
    static primaryKey = "name"

    // @desc    normalized data for the UI
    static fields () {
        return {
            name: this.string(),
            route: this.string(),
            successRoute: this.string(),
            successUrl: this.string()
        }
    }
}
```

### Expected result

I expect babel/Gridsome to respect `static` properties in a class structure as it did in v0.4.0 and compile correctly.

### Actual result

i receive the following parse/compilation error:

```
error  in ./src/components/forms/models.js

Module parse failed: Unexpected token (5:18)
You may need an appropriate loader to handle this file type.
| export class Form extends Model {
|     // @desc    object name within Vuex
>     static entity = "forms"
|
|     // // @desc    localized primary key

 @ ./src/store.js 5:0-47
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js
```

**Comment by courcelan** [comment]
Correction, it does seem that it can't parse anything inside a JS Class structure at all. Removing the `static` from the property still results in an unexpected token error. This leads me to believe Gridsome isn't seeing the `.babelrc` file

**Comment by courcelan** [comment]
This was corrected by 0.4.3 release. Thanks @hjvedvik
