### ISSUE TITLE
Default example for createServer API does not work

### ISSUE THREAD

**Issue by cco3** [gridsome/gridsome#668]
## Description

https://gridsome.org/docs/server-api/#apiconfigureserverfn

In `gridsome.server.js`

```
module.exports = function (api) {
  api.configureServer(app => {
    app.get('/my-endpoint', (req, res) => {
      res.send('Hello, world!')
    })
  })
}
```

Running `gridsome develop`, I hit `TypeError: gridsome.server.js: app.get is not a function`

### Environment

<pre><code>
- gridsome version: 0.7.2
</code></pre>

**Comment by hjvedvik** [comment]
This should work in v0.7.3 :)
